# Generated by Django 4.1.3 on 2022-11-20 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rofiq', '0002_order_product_alter_custumer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='custumer',
            options={'verbose_name_plural': 'Konsumen'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produk'},
        ),
        migrations.AddField(
            model_name='order',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rofiq.custumer'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rofiq.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='gambar/produk', verbose_name='Gambar (1200 x 700)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='rofiq.tag'),
        ),
    ]
