# Generated by Django 4.1.3 on 2022-11-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rofiq', '0003_tag_alter_custumer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumer',
            options={},
        ),
    ]
