# Generated by Django 4.1.3 on 2022-11-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rofiq', '0004_alter_custumer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custumer',
            options={'verbose_name_plural': 'Konsumen'},
        ),
    ]
